
package edu.txstate.cs4398.vc.desktop.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MobileServices", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MobileServices {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/", className = "edu.txstate.cs4398.vc.desktop.services.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/", className = "edu.txstate.cs4398.vc.desktop.services.EchoResponse")
    public String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addVideo", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/", className = "edu.txstate.cs4398.vc.desktop.services.AddVideo")
    @ResponseWrapper(localName = "addVideoResponse", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/", className = "edu.txstate.cs4398.vc.desktop.services.AddVideoResponse")
    public boolean addVideo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.txstate.cs4398.vc.desktop.services.Video
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVideoByUPC", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/", className = "edu.txstate.cs4398.vc.desktop.services.GetVideoByUPC")
    @ResponseWrapper(localName = "getVideoByUPCResponse", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/", className = "edu.txstate.cs4398.vc.desktop.services.GetVideoByUPCResponse")
    public Video getVideoByUPC(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductName", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/", className = "edu.txstate.cs4398.vc.desktop.services.GetProductName")
    @ResponseWrapper(localName = "getProductNameResponse", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/", className = "edu.txstate.cs4398.vc.desktop.services.GetProductNameResponse")
    public String getProductName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.txstate.cs4398.vc.desktop.services.Video
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVideoByName", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/", className = "edu.txstate.cs4398.vc.desktop.services.GetVideoByName")
    @ResponseWrapper(localName = "getVideoByNameResponse", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/", className = "edu.txstate.cs4398.vc.desktop.services.GetVideoByNameResponse")
    public Video getVideoByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
