
package edu.txstate.cs4398.vc.desktop.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MobileServices", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MobileServices {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/", className = "edu.txstate.cs4398.vc.desktop.services.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://services.desktop.vc.cs4398.txstate.edu/", className = "edu.txstate.cs4398.vc.desktop.services.EchoResponse")
    public String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
